// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bytecode

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OpPushStr struct {
	_tab flatbuffers.Table
}

func GetRootAsOpPushStr(buf []byte, offset flatbuffers.UOffsetT) *OpPushStr {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OpPushStr{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OpPushStr) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OpPushStr) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OpPushStr) Val() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func OpPushStrStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func OpPushStrAddVal(builder *flatbuffers.Builder, val flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(val), 0)
}
func OpPushStrEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
