// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bytecode

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OpPushBool struct {
	_tab flatbuffers.Table
}

func GetRootAsOpPushBool(buf []byte, offset flatbuffers.UOffsetT) *OpPushBool {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OpPushBool{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OpPushBool) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OpPushBool) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OpPushBool) Val() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *OpPushBool) MutateVal(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func OpPushBoolStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func OpPushBoolAddVal(builder *flatbuffers.Builder, val bool) {
	builder.PrependBoolSlot(0, val, false)
}
func OpPushBoolEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
