// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bytecode

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OpAdd struct {
	_tab flatbuffers.Table
}

func GetRootAsOpAdd(buf []byte, offset flatbuffers.UOffsetT) *OpAdd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OpAdd{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OpAdd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OpAdd) Table() flatbuffers.Table {
	return rcv._tab
}

func OpAddStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func OpAddEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
