// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bytecode

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OpDiv struct {
	_tab flatbuffers.Table
}

func GetRootAsOpDiv(buf []byte, offset flatbuffers.UOffsetT) *OpDiv {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OpDiv{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OpDiv) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OpDiv) Table() flatbuffers.Table {
	return rcv._tab
}

func OpDivStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func OpDivEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
