// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bytecode

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OpMul struct {
	_tab flatbuffers.Table
}

func GetRootAsOpMul(buf []byte, offset flatbuffers.UOffsetT) *OpMul {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OpMul{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OpMul) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OpMul) Table() flatbuffers.Table {
	return rcv._tab
}

func OpMulStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func OpMulEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
