// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bytecode

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OpPushFalse struct {
	_tab flatbuffers.Table
}

func GetRootAsOpPushFalse(buf []byte, offset flatbuffers.UOffsetT) *OpPushFalse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OpPushFalse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OpPushFalse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OpPushFalse) Table() flatbuffers.Table {
	return rcv._tab
}

func OpPushFalseStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func OpPushFalseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
