// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bytecode

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OpSysCall struct {
	_tab flatbuffers.Table
}

func GetRootAsOpSysCall(buf []byte, offset flatbuffers.UOffsetT) *OpSysCall {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OpSysCall{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OpSysCall) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OpSysCall) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OpSysCall) Args() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *OpSysCall) MutateArgs(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *OpSysCall) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func OpSysCallStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OpSysCallAddArgs(builder *flatbuffers.Builder, args uint16) {
	builder.PrependUint16Slot(0, args, 0)
}
func OpSysCallAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func OpSysCallEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
