// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bytecode

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Version struct {
	_tab flatbuffers.Struct
}

func (rcv *Version) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Version) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Version) Minor() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Version) MutateMinor(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Version) Major() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(1))
}
func (rcv *Version) MutateMajor(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(1), n)
}

func CreateVersion(builder *flatbuffers.Builder, minor byte, major byte) flatbuffers.UOffsetT {
	builder.Prep(1, 2)
	builder.PrependByte(major)
	builder.PrependByte(minor)
	return builder.Offset()
}
